In [52]:
import pandas as pd

# Load your data
df1 = pd.read_json("hf://datasets/NxtGenIntern/IT_Job_Roles_Skills_Certifications_Dataset/Top_207_IT_Job_Roles_Skills_Database.json")

# Step 1: Add backend_developer
backend_row = {
    "Job Title": "backend developer",
    "Job Description": (
        "Responsible for server-side web application logic and integration of "
        "the work front-end developers do. Designs, builds, and maintains APIs, "
        "databases, and application infrastructure to ensure high performance, "
        "security, and scalability."
    ),
    "Skills": ", ".join([
        "python",
        "java",
        "c++",
        "sql",
        "nosql",
        "rest apis",
        "docker",
        "kubernetes"
    ]),
    "Certifications": ", ".join([
        "AWS Certified Developer",
        "Oracle Java Certification",
        "Docker Certified Associate",
        "Kubernetes Application Developer"
    ])
}

df1 = pd.concat([df1, pd.DataFrame([backend_row])], ignore_index=True)

# Step 2: Lowercase job titles
df1['Job Title'] = df1['Job Title'].str.lower()

# Step 3: Map original names to model names
job_name_map = {
    "python developer": "python_developer",
    "java developer": "java_developer",
    "web developer": "web_developer",
    "database administrator": "database_administrator",
    "security specialist": "security_analyst",
    "systems administrator": "systems_administrator",
    "agile project manager": "project_manager",
    "front end developer": "frontend_developer",
    "network and systems administrator": "network_administrator",
    "software developer": "software_developer",
    "full stack developer": "fullstack_developer",
    "data scientist": "data_scientist",
    "mobile app developer": "mobile_app_developer",
    "cloud engineer": "cloud_engineer",
    "backend developer": "backend_developer",
    "machine learning engineer": "ml_engineer"
}

df1['Job Title'] = df1['Job Title'].map(job_name_map)

# Step 4: Keep only rows where the job is in model_jobs
model_jobs = list(job_name_map.values())
df1 = df1[df1['Job Title'].isin(model_jobs)].copy()
df1['Skills'] = df1['Skills'].str.lower()
df1.head()

,Job Title,Job Description,Skills,Certifications
24,ml_engineer,Builds machine learning models by implementing...,"python, machine learning, tensorflow, keras, p...",Microsoft Certified: Azure Data Scientist Asso...
40,project_manager,Manages Agile projects by facilitating Scrum c...,"agile methodologies, scrum, kanban, project ma...","Project Management Professional (PMP), Certifi..."
58,cloud_engineer,Builds and maintains cloud infrastructure. Res...,"cloud computing, aws, azure, google cloud, lin...","Google Cloud Associate Cloud Engineering, Comp..."
75,data_scientist,Utilizes statistical analysis and machine lear...,"python, r, machine learning, data science, sta...","Certified Analytics Professional (CAP), Micros..."
76,database_administrator,Responsible for managing database systems incl...,"sql, database management, mysql, postgresql, o...","Oracle Database SQL Certified Associate, Micro..."

In [53]:
skills_from_jobs = (
    df1['Skills']
    .str.split(',')
    .explode()
    .str.strip()
    .str.lower()
    .unique()
)

skills_from_jobs = set(skills_from_jobs)
df2 = pd.read_excel("../../ml/data/skills/skills_enriched.xlsx")
df2 = df2.drop(columns=['skill'])
df2 = df2.rename(columns={'skill_clean': 'skill'})
df2['skill'] = df2['skill'].str.strip().str.lower()
df2 = df2[df2['skill'].isin(skills_from_jobs)].copy()
skill_group_map = {
    "Software Engineering & Development": 1,
    "Web, Mobile & UI/UX Development": 2,
    "IT Operations, Networking & Systems": 3,
    "Cloud Computing & Platforms": 4,
    "Machine Learning & Artificial Intelligence": 5,
    "DevOps, SRE & Platform Engineering": 6,
    "Security, DevSecOps & Compliance": 7,
    "Data Engineering & Big Data": 8,
    "Data Science, Analytics & BI": 9,
    "Infrastructure as Code & Automation": 10
}
df2['skill_group_id'] = df2['skill_group'].map(skill_group_map)
missing_groups = df2[df2['skill_group_id'].isna()]['skill_group'].unique()

if len(missing_groups) > 0:
    raise ValueError(f"Unmapped skill groups found: {missing_groups}")

df2

,skill,skill_group,skill_description,skill_group_id
3,azure,Cloud Computing & Platforms,"Microsoft cloud platform for compute, storage,...",4
4,hadoop,Data Engineering & Big Data,Big data ecosystem for distributed storage and...,8
5,nosql,Software Engineering & Development,"Database technology used to store, query and m...",1
8,security,"Security, DevSecOps & Compliance","Controls and practices to secure systems, mana...",7
9,spark,Data Engineering & Big Data,Distributed processing engine for large-scale ...,8
...,...,...,...,...
382,windows server administration,"IT Operations, Networking & Systems","Operational skills to manage systems, networks...",3
383,linux administration,"IT Operations, Networking & Systems","Operational skills to manage systems, networks...",3
404,angularjs,"Web, Mobile & UI/UX Development",Technologies to build user-facing web/mobile e...,2
407,css3,Cloud Computing & Platforms,"Cloud services and platforms used to deploy, s...",4
408,html5,"Web, Mobile & UI/UX Development",Technologies to build user-facing web/mobile e...,2

In [56]:
# Split, normalize, and explode skills
df1_skills = (
    df1
    .assign(Skills=df1['Skills'].str.split(','))
    .explode('Skills')
)

df1_skills['Skills'] = (
    df1_skills['Skills']
    .str.strip()
    .str.lower()
)

# Drop duplicates just in case
df1_skills = df1_skills.drop_duplicates(
    subset=['Job Title', 'Skills']
)

# Build jobs_dict
jobs_dict = (
    df1_skills
    .groupby('Job Title')['Skills']
    .apply(list)
    .to_dict()
)

import json

with open("jobs_dict.json", "w", encoding="utf-8") as f:
    json.dump(jobs_dict, f, indent=2, ensure_ascii=False)

In [58]:
# Normalize skill names
df2['skill'] = df2['skill'].str.strip().str.lower()

skill_info = {
    row['skill']: {
        'group': row['skill_group'],
        'group_id': row['skill_group_id'],
        'description': row['skill_description']
    }
    for _, row in df2.iterrows()
}

with open("skills_info.json", "w", encoding="utf-8") as f:
    json.dump(skill_info, f, indent=2, ensure_ascii=False)

In [ ]:
df["Skills"] = df["Skills"].apply(lambda x: [s.strip() for s in x.split(",")])
df["Certifications"] = df["Certifications"].apply(lambda x: [c.strip() for c in x.split(",")])

In [ ]:
# Step 1: Create an empty dictionary to hold merged data
merged_data = {}

# Step 2: Loop over each row in the DataFrame
for index, row in df.iterrows():
    job = row["Job Title"]
    skills = row["Skills"]           # should be a list
    certifications = row["Certifications"]  # should be a list
    
    if job not in merged_data:
        merged_data[job] = {
            "Skills": set(skills),
            "Certifications": set(certifications)
        }
    else:
        merged_data[job]["Skills"].update(skills)
        merged_data[job]["Certifications"].update(certifications)

# Step 3: Convert the dictionary back to a DataFrame
df_merged = pd.DataFrame({
    "Job Title": list(merged_data.keys()),
    "Skills": [list(v["Skills"]) for v in merged_data.values()],
    "Certifications": [list(v["Certifications"]) for v in merged_data.values()]
})

df_merged.head()

,Job Title,Skills,Certifications
0,Admin Big Data,"[MapReduce, Data Lakes, Data Modeling, Cloud C...","[AWS Certified Big Data – Specialty, Hortonwor..."
1,Ansible Operations Engineer,"[Infrastructure as Code, Kubernetes, Ansible, ...","[AWS Certified DevOps Engineer – Professional,..."
2,Artifactory Administrator,"[Gradle, Build Automation, Git, CI/CD, Jenkins...","[DevOps Institute Certifications, JFrog Artifa..."
3,Artificial intelligence / Machine Learning Eng...,[],[]
4,Artificial Intelligence / Machine Learning Leader,"[Communication, Data Science, Project Manageme...",[Certified Artificial Intelligence Practitione...

In [8]:
df_merged.describe()

,Job Title,Skills,Certifications
count,200,200,200
unique,200,174,121
top,Admin Big Data,"[SQL, Algorithms, HTML, Data Structures, Git, ...",[]
freq,1,8,50

In [9]:
skill_dict = {}

for index, row in df.iterrows():
    job = row["Job Title"]
    for skill in row["Skills"]:
        skill_lower = skill.lower()
        if skill_lower not in skill_dict:
            skill_dict[skill_lower] = [job]
        else:
            skill_dict[skill_lower].append(job)

print(skill_dict)

{'hadoop': ['Admin Big Data', 'Big Data Architect', 'Big Data Engineer', 'Big Data Specialist', 'Principle Engineer in Big Data', 'Data Engineer', 'DATA SCIENTIST'], 'spark': ['Admin Big Data', 'Big Data Architect', 'Big Data Engineer', 'Big Data Specialist', 'Principle Engineer in Big Data', 'Data Engineer', 'DATA SCIENTIST'], 'mapreduce': ['Admin Big Data', 'Big Data Architect'], 'data lakes': ['Admin Big Data', 'Big Data Architect'], 'data warehousing': ['Admin Big Data', 'Big Data Architect', 'Big Data Engineer', 'Data Architect', 'Principle Engineer in Big Data', 'Data Engineer', 'DATA MODELER'], 'big data architecture': ['Admin Big Data', 'Principle Engineer in Big Data'], 'nosql': ['Admin Big Data', 'Big Data Architect', 'Big Data Engineer', 'Big Data Specialist', 'Data Architect'], 'data modeling': ['Admin Big Data', 'Big Data Architect', 'Big Data Specialist', 'Data Analysts', 'Data Architect', 'Principle Engineer in Data Analysis', 'DATA ANALYST', 'Data Engineer', 'DATA MODELER', 'Programmer Analyst', 'SQL Developer'], 'etl': ['Admin Big Data', 'Big Data Architect', 'Big Data Engineer', 'Big Data Specialist', 'Data Analysts', 'Data Architect', 'DATA ANALYST', 'Data Engineer', 'Oracle Developer', 'Oracle SQL Developer', 'SQL Developer'], 'cloud computing': ['Admin Big Data', 'Artifactory Administrator', 'Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'Artificial intelligence Architect', 'Big Data Architect', 'Big Data Engineer', 'Big Data Specialist', 'Chef Operations Engineer', 'Data Architect', 'DevOps Architect', 'DevOps Engineer', 'Kubernetes Operations Engineer', 'Machine learning Architect', 'Operations Engineer', 'Principle Engineer in Artificial Intelligence', 'Principle Engineer in Big Data', 'Principle Engineer in Machine Learning', 'Puppet Operations Engineer', 'Senior DevOps Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', '.NET Developer', 'Ansible Automation Engineer', 'AppDynamics Engineer', 'Artifactory Engineer', 'C# Developer', 'Chef InSpec Engineer', 'Cloud administrator', 'Cloud automation engineer', 'Cloud engineer', 'Consul Engineer', 'Data Engineer', 'DATA SCIENTIST', 'Datadog Engineer', 'DevOps Architect', 'DevOps Engineer', 'DEVOPS MANAGER', 'Docker Engineer', 'Envoy Engineer', 'Falco Engineer', 'FluentD Engineer', 'Full Stack JAVA Developer/Programmer/Engineer', 'Full Stack Python Developer/Programmer/Engineer', 'Grafana Engineer', 'Istio Engineer', 'IT Manager', 'Java Developer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Micro services / API Lead Designer', 'New Relic Engineer', 'Nomad Engineer', 'Octopus Deploy Engineer', 'OpenShift Engineer', 'OpenStack Engineer', 'Packer Engineer', 'Powershell Engineer', 'Prometheus Engineer', 'Puppet Engineer', 'Python Developer', 'Senior Ansible Development Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Software Engineer', 'SYSTEMS ENGINEER'], 'aws': ['Admin Big Data', 'Ansible Operations Engineer', 'Artificial intelligence Architect', 'Big Data Architect', 'Chef Operations Engineer', 'Data Architect', 'DevOps Architect', 'DevOps Engineer', 'ELK Engineer', 'Kubernetes Operations Engineer', 'Machine learning Architect', 'Puppet Operations Engineer', 'Senior DevOps Engineer', 'Splunk Engineer', 'Ansible Automation Engineer', 'AWS DevOps Engineer', 'AWS Solutions Architect', 'Cloud administrator', 'CLOUD ARCHITECT', 'Cloud automation engineer', 'Cloud engineer', 'Cloud network engineer', 'Cloud Security Engineer', 'DevOps Architect', 'DevOps Engineer', 'DevSecOps Engineer', 'ELK Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Packer Engineer', 'Puppet Engineer', 'Senior Ansible Development Engineer', 'Senior Cloud Architect', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Splunk Engineer', 'Terraform Engineer'], 'azure': ['Admin Big Data', 'Artificial intelligence Architect', 'Big Data Architect', 'Chef Operations Engineer', 'Data Architect', 'DevOps Architect', 'DevOps Engineer', 'ELK Engineer', 'Kubernetes Operations Engineer', 'Machine learning Architect', 'Puppet Operations Engineer', 'Senior DevOps Engineer', 'Splunk Engineer', 'Ansible Automation Engineer', 'Azure DevOps Engineer', 'Cloud administrator', 'CLOUD ARCHITECT', 'Cloud automation engineer', 'Cloud engineer', 'Cloud network engineer', 'Cloud Security Engineer', 'DevOps Architect', 'DevOps Engineer', 'ELK Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Packer Engineer', 'Puppet Engineer', 'Senior Ansible Development Engineer', 'Senior Cloud Architect', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Splunk Engineer', 'Terraform Engineer'], 'data governance': ['Admin Big Data', 'Big Data Architect', 'Data Architect', 'Principle Engineer in Big Data', 'DATA MODELER'], 'security': ['Admin Big Data', 'Artificial intelligence Architect', 'Big Data Architect', 'DevOps Architect', 'ELK Engineer', 'Kubernetes Operations Engineer', 'Machine learning Architect', 'Splunk Engineer', 'AWS Solutions Architect', 'Chef InSpec Engineer', 'Cloud administrator', 'Cloud engineer', 'Computer Network Architect', 'DevOps Architect', 'ELK Engineer', 'Envoy Engineer', 'Falco Engineer', 'Fortify Engineer', 'Information Security Analyst', 'Istio Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Micro services / API Lead Designer', 'Network Engineer', 'Notary Engineer', 'OpenShift Engineer', 'SECURITY SPECIALIST', 'Senior Cloud Architect', 'Senior DevOps Architect', 'SonarQube Engineer', 'Splunk Engineer'], 'ansible': ['Ansible Operations Engineer', 'DevOps Architect', 'DevOps Engineer', 'Senior DevOps Engineer', 'Ansible Automation Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'Cloud automation engineer', 'DevOps Architect', 'DevOps Engineer', 'DevSecOps Architect', 'GCP DevOps Engineer', 'Senior Ansible Development Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior DevSecOps Architect'], 'linux': ['Ansible Operations Engineer', 'Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'Chef Operations Engineer', 'DevOps Engineer', 'ELK Engineer', 'Gerrit Administrator', 'Jenkins Engineer', 'Kubernetes Operations Engineer', 'Operations Engineer', 'Production Support Engineer', 'Puppet Operations Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'Splunk Engineer', 'Ansible Automation Engineer', 'Artifactory Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'Chef InSpec Engineer', 'Cloud administrator', 'Cloud engineer', 'Datadog Engineer', 'DevOps Engineer', 'Docker Engineer', 'ELK Engineer', 'Entry Level Network Engineer', 'Full Stack Python Developer/Programmer/Engineer', 'GCP DevOps Engineer', 'Gerrit Engineer', 'Grafana Engineer', 'Jenkins Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Nagios Engineer', 'Network and Systems Administrator', 'Nomad Engineer', 'OpenShift Engineer', 'OpenStack Engineer', 'Puppet Engineer', 'Python Developer', 'Senior Ansible Development Engineer', 'Senior DevOps Engineer', 'Senior SRE Architect', 'Senior SRE Engineer', 'Splunk Engineer', 'SRE Engineer'], 'automation': ['Ansible Operations Engineer', 'Build and Release Engineer', 'Chef Operations Engineer', 'DevOps Architect', 'DevOps Engineer', 'Gerrit Administrator', 'Jenkins Engineer', 'Kubernetes Operations Engineer', 'Operations Engineer', 'Production Support Engineer', 'Puppet Operations Engineer', 'Senior Build and Release Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'Ansible Automation Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'Bamboo Engineer', 'Chef InSpec Engineer', 'Cloud administrator', 'CLOUD ARCHITECT', 'Cloud automation engineer', 'Cloud engineer', 'Consul Engineer', 'DevOps Architect', 'DevOps Engineer', 'DEVOPS MANAGER', 'Docker Engineer', 'GCP DevOps Engineer', 'Gerrit Engineer', 'Git Engineer', 'Github Engineer', 'GitLab Engineer', 'Groovy Engineer', 'Jenkins Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Network and Systems Administrator', 'Nomad Engineer', 'OpenShift Engineer', 'OpenStack Engineer', 'Packer Engineer', 'Powershell Engineer', 'Puppet Engineer', 'Senior Ansible Development Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior SRE Architect', 'Senior SRE Engineer', 'SRE Architect', 'SRE Engineer', 'UDeploy Engineer'], 'cloud platforms': ['Ansible Operations Engineer', 'Senior Site reliability Engineer', 'Senior SRE Architect', 'Senior SRE Engineer', 'SRE Engineer'], 'ci/cd': ['Ansible Operations Engineer', 'Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'DevOps Architect', 'DevOps Engineer', 'Jenkins Engineer', 'Kubernetes Operations Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'Artifactory Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'Bamboo Engineer', 'Bitbucket Engineer', 'CLOUD ARCHITECT', 'Cloud automation engineer', 'Coverage.py Engineer', 'DevOps Architect', 'DevOps Engineer', 'DEVOPS MANAGER', 'DevSecOps Architect', 'DevSecOps Engineer', 'Docker Engineer', 'Full Stack Developer', 'GCP DevOps Engineer', 'Git Engineer', 'Github Engineer', 'GitLab Engineer', 'Gradle Engineer', 'JaCoCO Engineer', 'Jenkins Engineer', 'JUnit Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'MAVEN Engineer', 'Nexus Engineer', 'Octopus Deploy Engineer', 'OpenShift Engineer', 'PyTest Engineer', 'QA Engineer', 'Selenium Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior DevSecOps Architect', 'Senior SRE Architect', 'Senior SRE Engineer', 'Software Engineer', 'SonarQube Engineer', 'SRE Architect', 'SRE Engineer', 'TeamCity Engineer', 'UDeploy Engineer', 'XL Deploy Engineer'], 'infrastructure as code': ['Ansible Operations Engineer', 'Chef Operations Engineer', 'Puppet Operations Engineer', 'Ansible Automation Engineer', 'Packer Engineer', 'Puppet Engineer', 'Senior Ansible Development Engineer'], 'kubernetes': ['Ansible Operations Engineer', 'Build and Release Engineer', 'DevOps Architect', 'DevOps Engineer', 'Jenkins Engineer', 'Kubernetes Operations Engineer', 'Senior Build and Release Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'CLOUD ARCHITECT', 'DevOps Architect', 'DevOps Engineer', 'DevSecOps Architect', 'DevSecOps Engineer', 'Docker Engineer', 'Envoy Engineer', 'Falco Engineer', 'GCP DevOps Engineer', 'Istio Engineer', 'Jenkins Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'OpenShift Engineer', 'Prometheus Engineer', 'Senior Cloud Architect', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior DevSecOps Architect', 'Senior SRE Architect', 'Senior SRE Engineer', 'SRE Architect', 'SRE Engineer'], 'docker': ['Ansible Operations Engineer', 'Artifactory Administrator', 'Build and Release Engineer', 'DevOps Architect', 'DevOps Engineer', 'Jenkins Engineer', 'Kubernetes Operations Engineer', 'Senior Build and Release Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'Artifactory Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'CLOUD ARCHITECT', 'DevOps Architect', 'DevOps Engineer', 'DevSecOps Architect', 'DevSecOps Engineer', 'Docker Engineer', 'Envoy Engineer', 'Falco Engineer', 'Full Stack Python Developer/Programmer/Engineer', 'GCP DevOps Engineer', 'Istio Engineer', 'Jenkins Engineer', 'kubernetes Administrator', 'Kubernetes Engineer', 'Nexus Engineer', 'Nomad Engineer', 'Notary Engineer', 'OpenShift Engineer', 'Prometheus Engineer', 'Python Developer', 'Senior Cloud Architect', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior DevSecOps Architect', 'Senior SRE Architect', 'Senior SRE Engineer', 'SRE Architect', 'SRE Engineer'], 'terraform': ['Ansible Operations Engineer', 'DevOps Architect', 'DevOps Engineer', 'Senior DevOps Engineer', 'AWS DevOps Engineer', 'AWS Solutions Architect', 'Azure DevOps Engineer', 'CLOUD ARCHITECT', 'Cloud automation engineer', 'DevOps Architect', 'DevOps Engineer', 'DevSecOps Architect', 'DevSecOps Engineer', 'GCP DevOps Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior DevSecOps Architect', 'Terraform Engineer'], 'python': ['Ansible Operations Engineer', 'Artificial Intelligence Researcher', 'Big Data Engineer', 'Data Analysts', 'DevOps Engineer', 'Machine Learning Engineer', 'Principle Engineer in Artificial Intelligence', 'Principle Engineer in Data Analysis', 'Principle Engineer in Machine Learning', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Ansible Automation Engineer', 'Cloud automation engineer', 'Computer Programmer', 'Coverage.py Engineer', 'DATA ANALYST', 'Data Engineer', 'DATA SCIENTIST', 'Developer', 'DevOps Engineer', 'Entry Level Developer', 'Entry Level Programmer', 'Entry Level Software Developer', 'Entry Level Software Engineer', 'FRAMEWORKS SPECIALIST', 'Full Stack Developer', 'Full Stack Python Developer/Programmer/Engineer', 'Jr Developer', 'Junior Developer', 'Junior Software Developer', 'Junior Software Engineer', 'Machine Learning Engineer', 'Micro services / API Lead Designer', 'New Grad Software Engineer', 'Programmer', 'PyTest Engineer', 'Python Developer', 'QA Engineer', 'Robotics Engineer', 'Selenium Engineer', 'Senior Ansible Development Engineer', 'Senior DevOps Engineer', 'Senior SRE Architect', 'Senior SRE Engineer', 'Software Developer', 'Software Engineer', 'SRE Engineer'], 'scripting': ['Ansible Operations Engineer', 'Build and Release Engineer', 'Build Engineer', 'DevOps Engineer', 'Gerrit Administrator', 'Jenkins Engineer', 'Operations Engineer', 'Production Support Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Splunk Engineer', 'Ansible Automation Engineer', 'AWS DevOps Engineer', 'Azure DevOps Engineer', 'Bamboo Engineer', 'Cloud administrator', 'Cloud automation engineer', 'Cloud engineer', 'DevOps Engineer', 'GCP DevOps Engineer', 'Gerrit Engineer', 'Git Engineer', 'Github Engineer', 'GitLab Engineer', 'Groovy Engineer', 'Jenkins Engineer', 'Nagios Engineer', 'Network and Systems Administrator', 'Octopus Deploy Engineer', 'OpenStack Engineer', 'Powershell Engineer', 'Senior Ansible Development Engineer', 'Splunk Engineer', 'SYSTEMS ADMINISTRATOR'], 'networking': ['Ansible Operations Engineer', 'DevOps Architect', 'DevOps Engineer', 'ELK Engineer', 'Kubernetes Operations Engineer', 'Operations Engineer', 'Production Support Engineer', 'Senior DevOps Engineer', 'Senior Site reliability Engineer', 'Site Reliability Engineer (Kubernetes – Docker)', 'Ansible Automation Engineer', 'AWS Solutions Architect', 'Cloud administrator', 'CLOUD ARCHITECT', 'Cloud engineer', 'Consul Engineer', 'DevOps Architect', 'DevOps Engineer', 'Docker Engineer', 'ELK Engineer', 'Entry Level Network Engineer', 'Envoy Engineer', 'Istio Engineer', 'IT Manager', 'kubernetes Administrator', 'Kubernetes Engineer', 'Nagios Engineer', 'Network and Systems Administrator', 'Nomad Engineer', 'OpenStack Engineer', 'Senior Ansible Development Engineer', 'Senior DevOps Architect', 'Senior DevOps Engineer', 'Senior SRE Architect', 'Senior SRE Engineer', 'SRE Architect', 'SYSTEMS ADMINISTRATOR', 'SYSTEMS ENGINEER'], 'artifactory': ['Artifactory Administrator', 'Artifactory Engineer'], 'jenkins': ['Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'DevOps Engineer', 'Jenkins Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Senior DevOps Engineer', 'Artifactory Engineer', 'DevOps Engineer', 'Full Stack JAVA Developer/Programmer/Engineer', 'Groovy Engineer', 'Java Developer', 'Jenkins Engineer', 'QA Engineer', 'Senior DevOps Engineer', 'Software Engineer'], 'maven': ['Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Artifactory Engineer', 'Full Stack JAVA Developer/Programmer/Engineer', 'Java Developer', 'MAVEN Engineer', 'Nexus Engineer'], 'gradle': ['Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Artifactory Engineer', 'Gradle Engineer', 'Nexus Engineer'], 'build automation': ['Artifactory Administrator', 'Build Engineer', 'Jenkins Engineer', 'Senior Build Engineer', 'Artifactory Engineer', 'Bamboo Engineer', 'Gradle Engineer', 'Groovy Engineer', 'Jenkins Engineer', 'MAVEN Engineer', 'Nexus Engineer', 'TeamCity Engineer'], 'version control': ['Artifactory Administrator', 'Build Engineer', 'Gerrit Administrator', 'Jenkins Engineer', 'Senior Build Engineer', 'Artifactory Engineer', 'Bamboo Engineer', 'Bitbucket Engineer', 'Gerrit Engineer', 'Git Engineer', 'Github Engineer', 'GitLab Engineer', 'Gradle Engineer', 'Jenkins Engineer', 'MAVEN Engineer', 'TeamCity Engineer', 'UDeploy Engineer', 'XL Deploy Engineer'], 'git': ['Artifactory Administrator', 'Build and Release Engineer', 'Build Engineer', 'DevOps Engineer', 'Gerrit Administrator', 'Senior Build and Release Engineer', 'Senior Build Engineer', 'Senior DevOps Engineer', '.NET Developer', 'Artifactory Engineer', 'Bamboo Engineer', 'Bitbucket Engineer', 'C# Developer', 'DevOps Engineer', 'Entry Level Developer', 'Entry Level Software Developer', 'Entry Level Software Engineer', 'Entry Level Web Developer', 'Full Stack JAVA Developer/Programmer/Engineer', 'Full Stack Python Developer/Programmer/Engineer', 'Gerrit Engineer', 'Git Engineer', 'Github Engineer', 'GitLab Engineer', 'Gradle Engineer', 'Java Developer', 'Jr Developer', 'Junior Developer', 'Junior Front End Developer', 'Junior IOS Developer', 'Junior Software Developer', 'Junior Software Engineer', 'Junior Web Developer', 'MAVEN Engineer', 'New Grad Software Engineer', 'PHP Developer', 'Python Developer', 'QA Engineer', 'React Developer', 'RUBY ON RAILS DEVELOPER', 'Senior DevOps Engineer', 'Software Engineer', 'TeamCity Engineer'], 'jfrog cli': ['Artifactory Administrator'], '': ['Artificial intelligence / Machine Learning Engineer', 'Twistkock Engineer'], 'ai strategy': ['Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'Principle Engineer in Artificial Intelligence'], 'machine learning': ['Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'Artificial intelligence Architect', 'Artificial Intelligence Researcher', 'Machine learning Architect', 'Machine Learning Engineer', 'Principle Engineer in Artificial Intelligence', 'Principle Engineer in Machine Learning', 'Computer Research Scientist', 'DATA SCIENTIST', 'Machine Learning Engineer'], 'team management': ['Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'DEVOPS MANAGER', 'Director of Engineering'], 'project management': ['Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'Jira Administrator', 'AGILE PROJECT MANAGER', 'DEVOPS MANAGER', 'Director of Engineering', 'IT Manager', 'JIRA Engineer', 'TECHNICAL ACCOUNT MANAGER', 'TECHNICAL LEAD'], 'data science': ['Artificial Intelligence / Machine Learning Leader', 'Artificial Intelligence / Machine Learning Sr.Leader', 'Artificial intelligence Architect', 'Machine learning Architect', 'Machine Learning Engineer', 'Principle Engineer in Artificial Intelligence', 'DATA SCIENTIST', 'Machine Learning Engineer'], 'deep learning': ['Artificial Intelligence / Machine Learning Leader', 'Artificial In

In [21]:
with open("alex.txt", "r") as f:
    text = f.read()  # read entire file as one string

words = text.split()
# Normalize to lowercase
words= [s.lower() for s in words]

# Count how many skills match per job
job_match_count = {}

for skill in words:
    if skill in skill_dict:
        for job in skill_dict[skill]:
            job_match_count[job] = job_match_count.get(job, 0) + 1

job_match_list = list(job_match_count.items())
job_match_list.sort(key=lambda item: item[1], reverse=True)
job_match_sorted = job_match_list
for job, count in job_match_sorted:
    print(f"{job}: {count} matching skills")

print(job_match_sorted)

DevOps Engineer: 10 matching skills
Machine Learning Engineer: 10 matching skills
Senior DevOps Engineer: 10 matching skills
Full Stack Developer: 9 matching skills
Full Stack Python Developer/Programmer/Engineer: 9 matching skills
Entry Level Developer: 8 matching skills
Entry Level Software Developer: 8 matching skills
Entry Level Software Engineer: 8 matching skills
Jr Developer: 8 matching skills
Junior Developer: 8 matching skills
Junior Software Developer: 8 matching skills
Junior Software Engineer: 8 matching skills
New Grad Software Engineer: 8 matching skills
Data Analysts: 7 matching skills
DATA ANALYST: 7 matching skills
DATA SCIENTIST: 7 matching skills
Python Developer: 7 matching skills
Big Data Engineer: 6 matching skills
Principle Engineer in Data Analysis: 6 matching skills
Data Engineer: 6 matching skills
FRAMEWORKS SPECIALIST: 6 matching skills
Ansible Operations Engineer: 5 matching skills
Artificial Intelligence Researcher: 5 matching skills
Principle Engineer in Artificial Intelligence: 5 matching skills
Principle Engineer in Machine Learning: 5 matching skills
Senior Site reliability Engineer: 5 matching skills
Ansible Automation Engineer: 5 matching skills
Cloud automation engineer: 5 matching skills
Computer Programmer: 5 matching skills
Coverage.py Engineer: 5 matching skills
Developer: 5 matching skills
Entry Level Programmer: 5 matching skills
Micro services / API Lead Designer: 5 matching skills
Programmer: 5 matching skills
PyTest Engineer: 5 matching skills
QA Engineer: 5 matching skills
Robotics Engineer: 5 matching skills
Selenium Engineer: 5 matching skills
Senior Ansible Development Engineer: 5 matching skills
Senior SRE Architect: 5 matching skills
Senior SRE Engineer: 5 matching skills
Software Developer: 5 matching skills
Software Engineer: 5 matching skills
SRE Engineer: 5 matching skills
Full Stack JAVA Developer/Programmer/Engineer: 3 matching skills
RUBY ON RAILS DEVELOPER: 3 matching skills
ACCESSIBILITY SPECIALIST: 2 matching skills
Entry Level Web Developer: 2 matching skills
Front End Developer: 2 matching skills
Front End Web Developer: 2 matching skills
JavaScript Developer: 2 matching skills
Junior Front End Developer: 2 matching skills
Junior Web Developer: 2 matching skills
PHP Developer: 2 matching skills
React Developer: 2 matching skills
Big Data Specialist: 1 matching skills
Data Architect: 1 matching skills
Android Developer: 1 matching skills
BUSINESS SYSTEMS ANALYST: 1 matching skills
Computer Systems Analyst: 1 matching skills
DATA MODELER: 1 matching skills
Database Administrator: 1 matching skills
IOS Developer: 1 matching skills
Java Developer: 1 matching skills
Oracle Developer: 1 matching skills
Oracle SQL Developer: 1 matching skills
Programmer Analyst: 1 matching skills
SQL Developer: 1 matching skills
[('DevOps Engineer', 10), ('Machine Learning Engineer', 10), ('Senior DevOps Engineer', 10), ('Full Stack Developer', 9), ('Full Stack Python Developer/Programmer/Engineer', 9), ('Entry Level Developer', 8), ('Entry Level Software Developer', 8), ('Entry Level Software Engineer', 8), ('Jr Developer', 8), ('Junior Developer', 8), ('Junior Software Developer', 8), ('Junior Software Engineer', 8), ('New Grad Software Engineer', 8), ('Data Analysts', 7), ('DATA ANALYST', 7), ('DATA SCIENTIST', 7), ('Python Developer', 7), ('Big Data Engineer', 6), ('Principle Engineer in Data Analysis', 6), ('Data Engineer', 6), ('FRAMEWORKS SPECIALIST', 6), ('Ansible Operations Engineer', 5), ('Artificial Intelligence Researcher', 5), ('Principle Engineer in Artificial Intelligence', 5), ('Principle Engineer in Machine Learning', 5), ('Senior Site reliability Engineer', 5), ('Ansible Automation Engineer', 5), ('Cloud automation engineer', 5), ('Computer Programmer', 5), ('Coverage.py Engineer', 5), ('Developer', 5), ('Entry Level Programmer', 5), ('Micro services / API Lead Designer', 5), ('Programmer', 5), ('PyTest Engineer', 5), ('QA Engineer', 5), ('Robotics Engineer', 5), ('Selenium Engineer', 5), ('Senior Ansible Development Engineer', 5), ('Senior SRE Architect', 5), ('Senior SRE Engineer', 5), ('Software Developer', 5), ('Software Engineer', 5), ('SRE Engineer', 5), ('Full Stack JAVA Developer/Programmer/Engineer', 3), ('RUBY ON RAILS DEVELOPER', 3), ('ACCESSIBILITY SPECIALIST', 2), ('Entry Level Web Developer', 2), ('Front End Developer', 2), ('Front End Web Developer', 2), ('JavaScript Developer', 2), ('Junior Front End Developer', 2), ('Junior Web Developer', 2), ('PHP Developer', 2), ('React Developer', 2), ('Big Data Specialist', 1), ('Data Architect', 1), ('Android Developer', 1), ('BUSINESS SYSTEMS ANALYST', 1), ('Computer Systems Analyst', 1), ('DATA MODELER', 1), ('Database Administrator', 1), ('IOS Developer', 1), ('Java Developer', 1), ('Oracle Developer', 1), ('Oracle SQL Developer', 1), ('Programmer Analyst', 1), ('SQL Developer', 1)]

In [22]:
with open("fiona.txt", "r") as f:
    text = f.read()  # read entire file as one string

words = text.split()
# Normalize to lowercase
words= [s.lower() for s in words]

# Count how many skills match per job
job_match_count = {}

for skill in words:
    if skill in skill_dict:
        for job in skill_dict[skill]:
            job_match_count[job] = job_match_count.get(job, 0) + 1

job_match_list = list(job_match_count.items())
job_match_list.sort(key=lambda item: item[1], reverse=True)
job_match_sorted = job_match_list
for job, count in job_match_sorted:
    print(f"{job}: {count} matching skills")

print(job_match_sorted)

Data Analysts: 4 matching skills
DevOps Engineer: 4 matching skills
Machine Learning Engineer: 4 matching skills
Senior DevOps Engineer: 4 matching skills
DATA ANALYST: 4 matching skills
Big Data Engineer: 3 matching skills
Principle Engineer in Data Analysis: 3 matching skills
Data Engineer: 3 matching skills
DATA SCIENTIST: 3 matching skills
Entry Level Developer: 3 matching skills
Entry Level Software Developer: 3 matching skills
Entry Level Software Engineer: 3 matching skills
Full Stack Developer: 3 matching skills
Full Stack Python Developer/Programmer/Engineer: 3 matching skills
Jr Developer: 3 matching skills
Junior Developer: 3 matching skills
Junior Software Developer: 3 matching skills
Junior Software Engineer: 3 matching skills
New Grad Software Engineer: 3 matching skills
Python Developer: 3 matching skills
WordPress Developer: 2 matching skills
Ansible Operations Engineer: 2 matching skills
Artificial Intelligence Researcher: 2 matching skills
Principle Engineer in Artificial Intelligence: 2 matching skills
Principle Engineer in Machine Learning: 2 matching skills
Senior Site reliability Engineer: 2 matching skills
Ansible Automation Engineer: 2 matching skills
Cloud automation engineer: 2 matching skills
Computer Programmer: 2 matching skills
Coverage.py Engineer: 2 matching skills
Developer: 2 matching skills
Entry Level Programmer: 2 matching skills
FRAMEWORKS SPECIALIST: 2 matching skills
Micro services / API Lead Designer: 2 matching skills
Programmer: 2 matching skills
PyTest Engineer: 2 matching skills
QA Engineer: 2 matching skills
Robotics Engineer: 2 matching skills
Selenium Engineer: 2 matching skills
Senior Ansible Development Engineer: 2 matching skills
Senior SRE Architect: 2 matching skills
Senior SRE Engineer: 2 matching skills
Software Developer: 2 matching skills
Software Engineer: 2 matching skills
SRE Engineer: 2 matching skills
Search Engine Optimization: 1 matching skills
Big Data Specialist: 1 matching skills
Data Architect: 1 matching skills
Android Developer: 1 matching skills
BUSINESS SYSTEMS ANALYST: 1 matching skills
Computer Systems Analyst: 1 matching skills
DATA MODELER: 1 matching skills
Database Administrator: 1 matching skills
Full Stack JAVA Developer/Programmer/Engineer: 1 matching skills
IOS Developer: 1 matching skills
Java Developer: 1 matching skills
Oracle Developer: 1 matching skills
Oracle SQL Developer: 1 matching skills
Programmer Analyst: 1 matching skills
RUBY ON RAILS DEVELOPER: 1 matching skills
SQL Developer: 1 matching skills
[('Data Analysts', 4), ('DevOps Engineer', 4), ('Machine Learning Engineer', 4), ('Senior DevOps Engineer', 4), ('DATA ANALYST', 4), ('Big Data Engineer', 3), ('Principle Engineer in Data Analysis', 3), ('Data Engineer', 3), ('DATA SCIENTIST', 3), ('Entry Level Developer', 3), ('Entry Level Software Developer', 3), ('Entry Level Software Engineer', 3), ('Full Stack Developer', 3), ('Full Stack Python Developer/Programmer/Engineer', 3), ('Jr Developer', 3), ('Junior Developer', 3), ('Junior Software Developer', 3), ('Junior Software Engineer', 3), ('New Grad Software Engineer', 3), ('Python Developer', 3), ('WordPress Developer', 2), ('Ansible Operations Engineer', 2), ('Artificial Intelligence Researcher', 2), ('Principle Engineer in Artificial Intelligence', 2), ('Principle Engineer in Machine Learning', 2), ('Senior Site reliability Engineer', 2), ('Ansible Automation Engineer', 2), ('Cloud automation engineer', 2), ('Computer Programmer', 2), ('Coverage.py Engineer', 2), ('Developer', 2), ('Entry Level Programmer', 2), ('FRAMEWORKS SPECIALIST', 2), ('Micro services / API Lead Designer', 2), ('Programmer', 2), ('PyTest Engineer', 2), ('QA Engineer', 2), ('Robotics Engineer', 2), ('Selenium Engineer', 2), ('Senior Ansible Development Engineer', 2), ('Senior SRE Architect', 2), ('Senior SRE Engineer', 2), ('Software Developer', 2), ('Software Engineer', 2), ('SRE Engineer', 2), ('Search Engine Optimization', 1), ('Big Data Specialist', 1), ('Data Architect', 1), ('Android Developer', 1), ('BUSINESS SYSTEMS ANALYST', 1), ('Computer Systems Analyst', 1), ('DATA MODELER', 1), ('Database Administrator', 1), ('Full Stack JAVA Developer/Programmer/Engineer', 1), ('IOS Developer', 1), ('Java Developer', 1), ('Oracle Developer', 1), ('Oracle SQL Developer', 1), ('Programmer Analyst', 1), ('RUBY ON RAILS DEVELOPER', 1), ('SQL Developer', 1)]

In [29]:
with open("fiona_eng.txt", "r") as f:
    text = f.read()  # read entire file as one string

words = text.split()
# Normalize to lowercase
words= [s.lower() for s in words]

# Count how many skills match per job
job_match_count = {}

for skill in words:
    if skill in skill_dict:
        for job in skill_dict[skill]:
            job_match_count[job] = job_match_count.get(job, 0) + 1

job_match_list = list(job_match_count.items())
job_match_list.sort(key=lambda item: item[1], reverse=True)
job_match_sorted = job_match_list
for job, count in job_match_sorted:
    print(f"{job}: {count} matching skills")

print(job_match_sorted)

Data Analysts: 4 matching skills
DevOps Engineer: 4 matching skills
Machine Learning Engineer: 4 matching skills
Senior DevOps Engineer: 4 matching skills
DATA ANALYST: 4 matching skills
Search Engine Optimization: 3 matching skills
Artificial Intelligence / Machine Learning Leader: 3 matching skills
Artificial Intelligence / Machine Learning Sr.Leader: 3 matching skills
AGILE PROJECT MANAGER: 3 matching skills
DEVOPS MANAGER: 3 matching skills
Director of Engineering: 3 matching skills
PRODUCT MANAGER: 3 matching skills
Confluence Engineer: 3 matching skills
Big Data Engineer: 3 matching skills
Principle Engineer in Data Analysis: 3 matching skills
Data Engineer: 3 matching skills
DATA SCIENTIST: 3 matching skills
Entry Level Developer: 3 matching skills
Entry Level Software Developer: 3 matching skills
Entry Level Software Engineer: 3 matching skills
Full Stack Developer: 3 matching skills
Full Stack Python Developer/Programmer/Engineer: 3 matching skills
Jr Developer: 3 matching skills
Junior Developer: 3 matching skills
Junior Software Developer: 3 matching skills
Junior Software Engineer: 3 matching skills
New Grad Software Engineer: 3 matching skills
Python Developer: 3 matching skills
WordPress Developer: 2 matching skills
Ansible Operations Engineer: 2 matching skills
Artificial Intelligence Researcher: 2 matching skills
Principle Engineer in Artificial Intelligence: 2 matching skills
Principle Engineer in Machine Learning: 2 matching skills
Senior Site reliability Engineer: 2 matching skills
Ansible Automation Engineer: 2 matching skills
Cloud automation engineer: 2 matching skills
Computer Programmer: 2 matching skills
Coverage.py Engineer: 2 matching skills
Developer: 2 matching skills
Entry Level Programmer: 2 matching skills
FRAMEWORKS SPECIALIST: 2 matching skills
Micro services / API Lead Designer: 2 matching skills
Programmer: 2 matching skills
PyTest Engineer: 2 matching skills
QA Engineer: 2 matching skills
Robotics Engineer: 2 matching skills
Selenium Engineer: 2 matching skills
Senior Ansible Development Engineer: 2 matching skills
Senior SRE Architect: 2 matching skills
Senior SRE Engineer: 2 matching skills
Software Developer: 2 matching skills
Software Engineer: 2 matching skills
SRE Engineer: 2 matching skills
Big Data Specialist: 1 matching skills
Data Architect: 1 matching skills
Android Developer: 1 matching skills
BUSINESS SYSTEMS ANALYST: 1 matching skills
Computer Systems Analyst: 1 matching skills
DATA MODELER: 1 matching skills
Database Administrator: 1 matching skills
Full Stack JAVA Developer/Programmer/Engineer: 1 matching skills
IOS Developer: 1 matching skills
Java Developer: 1 matching skills
Oracle Developer: 1 matching skills
Oracle SQL Developer: 1 matching skills
Programmer Analyst: 1 matching skills
RUBY ON RAILS DEVELOPER: 1 matching skills
SQL Developer: 1 matching skills
[('Data Analysts', 4), ('DevOps Engineer', 4), ('Machine Learning Engineer', 4), ('Senior DevOps Engineer', 4), ('DATA ANALYST', 4), ('Search Engine Optimization', 3), ('Artificial Intelligence / Machine Learning Leader', 3), ('Artificial Intelligence / Machine Learning Sr.Leader', 3), ('AGILE PROJECT MANAGER', 3), ('DEVOPS MANAGER', 3), ('Director of Engineering', 3), ('PRODUCT MANAGER', 3), ('Confluence Engineer', 3), ('Big Data Engineer', 3), ('Principle Engineer in Data Analysis', 3), ('Data Engineer', 3), ('DATA SCIENTIST', 3), ('Entry Level Developer', 3), ('Entry Level Software Developer', 3), ('Entry Level Software Engineer', 3), ('Full Stack Developer', 3), ('Full Stack Python Developer/Programmer/Engineer', 3), ('Jr Developer', 3), ('Junior Developer', 3), ('Junior Software Developer', 3), ('Junior Software Engineer', 3), ('New Grad Software Engineer', 3), ('Python Developer', 3), ('WordPress Developer', 2), ('Ansible Operations Engineer', 2), ('Artificial Intelligence Researcher', 2), ('Principle Engineer in Artificial Intelligence', 2), ('Principle Engineer in Machine Learning', 2), ('Senior Site reliability Engineer', 2), ('Ansible Automation Engineer', 2), ('Cloud automation engineer', 2), ('Computer Programmer', 2), ('Coverage.py Engineer', 2), ('Developer', 2), ('Entry Level Programmer', 2), ('FRAMEWORKS SPECIALIST', 2), ('Micro services / API Lead Designer', 2), ('Programmer', 2), ('PyTest Engineer', 2), ('QA Engineer', 2), ('Robotics Engineer', 2), ('Selenium Engineer', 2), ('Senior Ansible Development Engineer', 2), ('Senior SRE Architect', 2), ('Senior SRE Engineer', 2), ('Software Developer', 2), ('Software Engineer', 2), ('SRE Engineer', 2), ('Big Data Specialist', 1), ('Data Architect', 1), ('Android Developer', 1), ('BUSINESS SYSTEMS ANALYST', 1), ('Computer Systems Analyst', 1), ('DATA MODELER', 1), ('Database Administrator', 1), ('Full Stack JAVA Developer/Programmer/Engineer', 1), ('IOS Developer', 1), ('Java Developer', 1), ('Oracle Developer', 1), ('Oracle SQL Developer', 1), ('Programmer Analyst', 1), ('RUBY ON RAILS DEVELOPER', 1), ('SQL Developer', 1)]